### PR TITLE
Updated Dockerfile for Client Image

### PR DESCRIPTION
**Pull request by braughtg**
This PR updates the the KitClient image.  It does the following:
* Updates the `src` directory with a new Dockerfile and supporting configuration files and scripts. 
  * This new image is created from the `debian:bullseye` image which avoids issues of relying on `accetto/ubuntu-vnc-xfce-firefox-g3` (as in #24).
  * It installs XFCE, TigerVNC and NoVNC using apt so they will be up to date.
  * It installs firefox-esr as a browser in the container.
  * It install VSCodium instead of VSCode as experience suggests that it is more stable when running inside of a docker container.
  * It creates a user named `gitkit` as opposed to `headless`
  * It automatically logs `gitkit` in so there is no need for a password when connecting via VNC or noVNC.
  * It configures the XFCE Terminal to display emoji fonts so that Git Kit-TTY works correctly.
  * It adds Mousepad, VSCodium and firefox to the launcher panel at the bottom of the desktop.
  * It pre-configures a number of `git` options so that students do not need to do them in the activities.
* Updates `README.md` to reflect the above changes (see "Note on Versions" and "Discussion for this PR" sections below).
* Provides a `build.bash` script that creates and pushes multiarchitecture images (amd64 and arm64).

## Working Sample:
A working sample of the container created from these changes can be run with the command:
```bash
docker run --rm --name KitClient --detach --mount source=gitkitvol-22.10,target=/home/gitkit -p 6901:6901 -p 5901:5901 farmdata2/gitkitclient:22.10
```

## Things that are not quite right with this draft PR:
* `build.bash` pushes the images to `farmdata2` on dockerhub and not to `ghcr.io/hfossedu/kitclient` (because that's how I could test it).
* The `build.bash` script is in the `src` directory and should moved to the `bin`  directory when it is cleaned up to work with `ghcr.io/hfossedu/kitclient`

## Note on Versions:
* The `kitclient` image is tagged with a `yy.mm` tag.  This is reflected in the commands in the `README.md` file. 
* The commands in the `README.md` file also use a  `yy.mm` tag on the Docker volume used for the `gitkit` user's home directory. 
* This versioning is done so that if the image is updated a new image will be pulled and a new volume will be created.  This avoids many issues that can happen if a new image is pulled but an existing volume is used (e.g. config files in the volume are not overwritten by those in the new image).

## Discussion for this PR:
* The `gitkit` user is in the `sudo` group.  Do we want or need this?  
  * It might be nice to have, but also, any changes are lost when the container is stopped and restarted.
* The versioning is functional, but some additional thought should be given to whether it is the best solution.
  * It would be nice to be able to just use `latest` by default, but that does create a problem if the latest requires a clean `gitkit` home directory.

### CODE REVIEW

**Comment by StoneyJackson** [comment]
Regarding:  **The gitkit user is in the sudo group. Do we want or need this?**

1. It might be needed for kits to install additional applications into the client. A kit would do something like `sudo apt-get update && sudo apt-get install SPLAT` and the user would type the password for gitkit, and off it goes.
2. It might be needed for an instructor wanting to introduce students to an application that is not provided by a kit. In such cases, the instructor can tell students to type `sudo apt-get update && sudo apt-get install SPLAT` and the password for gitkit, and off it goes.

**Comment by StoneyJackson** [comment]
Regarding: **The versioning is functional, but some additional thought should be given to whether it is the best solution.
It would be nice to be able to just use latest by default, but that does create a problem if the latest requires a clean gitkit home directory.**

I don't understand. "latest" of what? Debian? And what does this have to do with the gitkit home directory? I'm assuming configuration files. Can you elaborate and/or give an example?

**Comment by braughtg** [comment]
Just noticed that the noVNC server does not seem to be responding.  VNC works fine.  I will update later today.

**Comment by braughtg** [comment]
> I don't understand. "latest" of what? Debian? And what does this have to do with the gitkit home directory? I'm assuming configuration files. Can you elaborate and/or give an example?

I was referring to having a "latest" tag of the KitClient image available for use with the run command.  So that the default documentation would always be the same regardless of the version and wouldn't need to be updated.  Same for the command that appears in the first activity.  That it it could just be something like hfossedu/KitClient:latest instead of hfossedu/KitClient:22.10 and wouldn't need to change each time we make a new KitClient image.

This has to do with the gitkit home directory because that is being mounted from a Docker volume instead of from a directory in the user's host OS file system.  This volume is created by the run command the first time it is mounted in to a container.  Its contents then persist across runs of the container.  So it preserves the contents of the home directory in the same way mounting from the host file system did.  

The catch is that the first time this volume is mounted it is empty and it is populated by the contents of the gitkit home directory, because it is mounted over that directory.  After that, this volume's contents supersede any contents that exist in the gitkit home directory in the image/container. 

The issue then arrises if a new image is created and used (i.e. the "latest" is replaced).  In that case, the gitkit home directory in the image might contain updated (and possibly incompatible) configuration information and scripts that are used by the container.  However, they will not get copied in to the gitkit home directory because of how the mount works.  I don't think this is unique to Docker volumes, but is also the same with volumes mounted from the host os.

So Using version numbers in the run command addresses this issue. If we bump the image version, we just change the run command to bump both the image version and the volume version.  Then anyone that had an old volume already would automatically get a new one and no issues occur.  The down side to using the version numbers is that the run command has to be updated anytime we update the KitClient.

**Comment by braughtg** [comment]
> * It might be needed for kits to install additional applications into the client. A kit would do something like `sudo apt-get update && sudo apt-get install SPLAT` and the user would type the password for gitkit, and off it goes.
> * It might be needed for an instructor wanting to introduce students to an application that is not provided by a kit. In such cases, the instructor can tell students to type `sudo apt-get update && sudo apt-get install SPLAT` and the password for gitkit, and off it goes.

I agree with these.  the only thing would be that those things that are installed would not persist across runs.  The run command we give removes the container when it is stopped.  So while the user's home directory is preserved (on the mounted volume) the remainder of the writeable layer in the container is deleted.

If we want the writeable layer to be preserved as well, we could remove the `-rm` from the `run` command.  Then the container would not be deleted when it is stopped.  If we do that, we may need to use the `create` and `start` commands instead of `run`.

**Comment by braughtg** [comment]
> * Debian is arguably more likely to be maintained because it is a bigger, mainstream effort backed by many developers.

I agree on this point. The image that we build from here is unlikely to go away anytime soon.

> * ubuntu-vnc-xfce-g3 is little over a year old (https://github.com/accetto/ubuntu-vnc-xfce-g3/) and looks like it's maintained by a single person. It has 50K+ pulls on DockerHub (https://hub.docker.com/r/accetto/ubuntu-vnc-xfce-firefox-g3).

As this image is not being kept up with the underlying Debian image there may be issues with pinned versions of the other things that we install.  This happened when I tried to rebuild the KitClient image from the Dockerfile that is presently in main.  Many of the pinned versions of packages no longer exist.

I can imagine this being a much bigger issue when doing a kit for some type of development where the specific versions of libraries are necessary.  Here I would argue that we are probably okay just using the latest versions of things like vim, nano, xfce, etc...

> * Relying on Debian requires that we need to know how to setup a working vnc, xfce, firefox, and so on inside of Docker. If we depend on ubuntu-vnc-xfce-g3 we are outsourcing that knowledge and support.

This is done in the Dockerfile in this PR.  Getting vnc / noVNC up and running was a little tricky, but not terrible. Configuring xfce to bet the way I wanted it was a little more work but isn't terrible now that there is a template in this PR. Firefox was just an apt install.

> * Relying on ubuntu-vnc-xfce-g3 means we are subject to that author's whims about what comes prepackaged, the configuration, etc. That is we don't have full control. But then we don't have to update any of this either.

The only time we would need to do any updates to xfce, vnc, noVNC would be when we generate a new KitClient image. So I think the question here is, how often do we anticipate needing to update the KitClient image that users will pull with the `run` command?  My guess is that once we have a stable KitClient image it won't be very often.

> I've been struggling with this question for a while now, and I don't have a good answer. Can anyone provide a convincing argument one way or the other? Or do we just need to pick one and recognize what we are getting ourselves into?

I don't know if that is a convincing argument or not, but I'm leaning toward building the KitClient image from the Debian base image.

**Comment by StoneyJackson** [comment]
> > I don't understand. "latest" of what? Debian? And what does this have to do with the gitkit home directory? I'm assuming configuration files. Can you elaborate and/or give an example?
> 
> I was referring to having a "latest" tag of the KitClient image available for use with the run command. So that the default documentation would always be the same regardless of the version and wouldn't need to be updated. Same for the command that appears in the first activity. That it it could just be something like hfossedu/KitClient:latest instead of hfossedu/KitClient:22.10 and wouldn't need to change each time we make a new KitClient image.

Can we pin to a major version instead of latest? So hfossedu/KitClient:22 . Assuming we are using SemVer and updating the major tag to the most recent minor and patch release within a major version, then clients will receive the latest version that does not contain a breaking change. More, the only time we would need to change the documentation would be if there is a possibly backwards incompatible change, which should require a review of the documentation and activity anyway.

Pinning to latest would allow the possibility of someone deploying GitKit, and then during their class we push an update to a component like KitClient causing breakage in the middle of their class (by middle, I mean over the course of a few days).

Or am I just being overly careful here?

 
> This has to do with the gitkit home directory because that is being mounted from a Docker volume instead of from a directory in the user's host OS file system. This volume is created by the run command the first time it is mounted in to a container. Its contents then persist across runs of the container. So it preserves the contents of the home directory in the same way mounting from the host file system did.
> 
> The catch is that the first time this volume is mounted it is empty and it is populated by the contents of the gitkit home directory, because it is mounted over that directory. After that, this volume's contents supersede any contents that exist in the gitkit home directory in the image/container.
> 
> The issue then arrises if a new image is created and used (i.e. the "latest" is replaced). In that case, the gitkit home directory in the image might contain updated (and possibly incompatible) configuration information and scripts that are used by the container. However, they will not get copied in to the gitkit home directory because of how the mount works. I don't think this is unique to Docker volumes, but is also the same with volumes mounted from the host os.
> 
> So Using version numbers in the run command addresses this issue. If we bump the image version, we just change the run command to bump both the image version and the volume version. Then anyone that had an old volume already would automatically get a new one and no issues occur. The down side to using the version numbers is that the run command has to be updated anytime we update the KitClient.

Thanks for the great explanation! I think I've got it now.

I can think of a complicated system for migrating files between images, but it always sounds like I'm re-inventing git. So I wonder if there is a way to make use of git inside the container to update files safely. For example, maybe we keep a repository of the home directory in a different location. Then the /home/gitkit is a clone of that directory. When a new update comes out, the entrypoint script pulls in /home/gitkit . There may be conflicts, but nothing would be lost. But conflicts would cause breakage. I think we could add an option to always resolve conflicts by keeping theirs. But then the configuration may be wrong for the kit, but maybe it would still work.

All of this sounds like a big mess. I would think the GitKit and the KitClient are fairly temporary. And I think it's more important that they work as intended with the deployment their instructor created than it is to keep them up-to-date with the latest and greatest.

Let's think and talk more and see what we can come up with.

**Comment by braughtg** [comment]
> Can we pin to a major version instead of latest? So hfossedu/KitClient:22 . Assuming we are using SemVer and updating the major tag to the most recent minor and patch release within a major version, then clients will receive the latest version that does not contain a breaking change. More, the only time we would need to change the documentation would be if there is a possibly backwards incompatible change, which should require a review of the documentation and activity anyway.

This sounds like a reasonable approach to me.

**Comment by braughtg** [comment]
> All of this sounds like a big mess. I would think the GitKit and the KitClient are fairly temporary. And I think it's more important that they work as intended with the deployment their instructor created than it is to keep them up-to-date with the latest and greatest.

I also agree with this.  They are temporary and as long as the `run` command they are given in the activity keeps working for the duration of use I think we are good.  So just using semantic versioning and pinning the image and the Docker volume to the major version in the `run` command addresses the issue sufficiently.

**Comment by StoneyJackson** [comment]
Let's change `gitkit` username to something more general since this client can be used by other kits.

Here is a brainstorm of other names:

* `kit`
* `kitclient`
* `client`
* `user`

**Comment by braughtg** [comment]
I forgot probably the most important reason to consider building from debian directly... It allows us to build the multarchitecture image.  The accetto/ubuntu-vnc-xfce-firefox-g3 only provides an amd64 image and thus an arm64 native image cannot be build from that base image.

**Comment by StoneyJackson** [comment]
@braughtg  I'm sold. Let's base KitClient on Debian directly.

**Comment by braughtg** [comment]
Replaced by #35.

**Pull request closed without merging**
